# Generated by Django 3.0 on 2019-12-19 20:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_stamp', models.DateTimeField(auto_now_add=True)),
                ('end_stamp', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=2, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('profile', models.CharField(max_length=100, null=True)),
                ('activities', models.CharField(max_length=50, null=True)),
                ('salary', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('text', models.CharField(max_length=200)),
                ('section', models.IntegerField(choices=[(1, 'Profile'), (2, 'Skills'), (3, 'Wages')], default=1)),
                ('type', models.CharField(choices=[('text', 'Text'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], default='text', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('helptext', models.CharField(blank=True, max_length=200, null=True)),
                ('required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuesta.Question')),
            ],
            options={
                'ordering': ['order', 'text'],
            },
        ),
    ]
