# Generated by Django 3.0 on 2019-12-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='maxlength',
            field=models.IntegerField(default=10),
        ),
    ]
