# Generated by Django 3.0 on 2019-12-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20191219_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='maxlength',
        ),
    ]
