# Generated by Django 3.0 on 2019-12-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_remove_question_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='edutype',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], default='text', max_length=10),
        ),
    ]
