# Generated by Django 3.0 on 2019-12-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_auto_20191220_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='emptype',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='orgtype',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='edutype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
