# Generated by Django 3.0 on 2019-12-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0006_auto_20191220_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='lang',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
