# Generated by Django 3.0 on 2019-12-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0007_answer_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='seniority',
            field=models.IntegerField(null=True),
        ),
    ]
