# Generated by Django 3.0 on 2019-12-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0009_question_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='front',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
