# Generated by Django 3.0 on 2019-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0010_answer_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='maxvalue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='minvalue',
            field=models.IntegerField(null=True),
        ),
    ]
