# Generated by Django 3.0 on 2019-12-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0011_auto_20191220_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=50)),
                ('answerset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.AnswerSet')),
            ],
        ),
    ]
