# Generated by Django 3.0 on 2019-12-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0012_answeritem_answerset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeritem',
            old_name='text',
            new_name='slug',
        ),
    ]
