# Generated by Django 4.0.1 on 2022-01-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0016_auto_20201120_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
